### ISSUE TITLE
Make `AppState` extensible

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#100]
### Description

The goal is to make the `AppState` struct extendable.
We want to make this possible by adding an extra field called `extensions`.
This field will be a hashmap of type `<String, Box<dyn>>`.
This will allow for any size of struct to be added as an extension, indexable by extension name.

### Motivation

The motivation is to move toward an app extendable in a clear and safe way.

After this issue (and the issues regarding Actions and Reducers, and UserPrompts) third party back-end developers should have no issue extending their version of our codebase.

Further down the road lies the task to format the rest of our code to the same format, forcing us to make our codebase clearly split up in neatly isolated building blocks.

### Resources

Depends on #92 

### To-do List

- [x] Add the extension field to the `AppState`
- [x] Add impl {pub fn extensions} to Appstate_container
- [x] Create tests with simple extensions and actions to interact with the extension
