### ISSUE TITLE
[Task] DX: apply formatting on repository level (using prettier)

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#128]
### Description

Since the split into two main folders: `unime` and `identity-wallet`, formatting rules applied through `prettier` only work if explicitly executed through `npm run format` and not respected by the IDE (VS Code) as there is no more `prettierrc` config on root level. Other repositories such as [Tauri](https://github.com/tauri-apps/tauri) have a `package.json` and `prettierrc` on the repository's root level, although they're mainly Rust and possibly rather formatted through `cargo fmt`.

### Motivation

Fix broken "Format on save" which is not detecting a formatter config due to it being moved from root level to `unime` folder.

### To-do List

- [x] Introduce global `prettierrc`
- [x] Configure `prettierignore` to ignore `identity-wallet` folder
- [x] Reenabling "Format on save" and running `npm run format` inside `unime` should produce the same result
