### ISSUE TITLE
Alter identity_wallet/src-tauri folder structure

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#130]
### Description

Create a clearer and easier to expand upon codebase structure. 
The idea is to split all features of the appstate into seperate folders which follow the redux pattern.
Some other files will also moved around to clean up a bit.

### Motivation

Clearer, easier to understand, use and navigate codebase structure

### To-do List

Restructuring existing codebase

- [ ] Split state code up in feat-state folders
- [ ] Work through remaining code, actions, reducers etc. to function with the new structure.
- [ ] Edit testing to comply with new structure
