### ISSUE TITLE
ci: run linter and tests on each new PR

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#14]
### Description

Add a GitHub Action that runs linters and all tests for both frontend (JS) and backend (Rust) and reports the results back to the open PR, so the reviewer can see them.

### Motivation

Automate code quality checks.

### To-do List

- [x] Lint & test Svelte frontend
- [ ] Lint & test Rust backend
- [ ] Adjust repo settings (report has to be successful as a merge requirement)
