### ISSUE TITLE
Refactor: Reorganize identity_wallet folder structure

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#140]
### Description

Reorganise the folders and files to isolate features more and make the redux pattern leading in the folder structure.

### Motivation

The folder structure doesn't yet follow our features and their redux pattern yet.

### To-do List

- [x] Move all non redux specific code (appstate/action/reducer) out of state folder and group them together more intuitively
- [x] Abstract oid4vc heavy code more to the background 
- [x] Restructure the state folder to into feature-folders with their respective mod.rs, actions.rs and reducers.rs files
