### ISSUE TITLE
Add tests to some of the Rust functions

### ISSUE THREAD

**Issue by Norlock** [impierce/identity-wallet#154]
### Description

The following functions still need a unit test:

- send_credential_request
- handle_oid4vp_authorization_request
- handle_siopv2_authorization_request

This needs to test if the connections/credentials are correctly accepted and if the history event is correctly added.

### Motivation

We need to better know if we break existing code when we make changes to the code base

### To-do List

- [ ] Add unit tests for send_credential_request
- [ ] Add unit tests for handle_oid4vp_authorization_request
- [ ] Add unit tests for handle_siopv2_authorization_request

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests to some of the Rust functions](https://trello.com/c/4IK7KRlA/23-add-tests-to-some-of-the-rust-functions)
