### ISSUE TITLE
feat: add connection info to interactions other than accept connection

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#155]
### Description

Since all interactions require a connection first, all these interactions, namely "accept credentials" & "share credentials", should have info regarding the underlying connection as well. This issue requires UX, FE and BE integration. 

To not over-complicate the user flow the other actions should stick to their current user flow, namely one button to accept or reject that action. However, they should also list connection information. It's up for discussion how much info and how we will arrange it on the screen. Information-wise, ideally it would be all the info we see when we get the "accept/reject connection" screen. But considering UX and presentation we will have to decide on what works best.

### Motivation

The user should always be informed about the connection they're about the approve.

### Resources

Related to #125 

### To-do List

- [ ] Decide on UX Design
- [ ] BE: Add connection info to User_Prompt::Credential_Offer & Share_Credentials
- [ ] FE: Display connection info in the desired way on user prompt screen

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [feat: add connection info to interactions other than accept connection](https://trello.com/c/8ue43udr/24-feat-add-connection-info-to-interactions-other-than-accept-connection)
