### ISSUE TITLE
chore(frontend): remove commented code, enhance DX, remove outdated feature

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#161]
### Description

* remove outdated commented code
* remove unused feature: change appearance of credential (color, icon)
* add demo history to Ferris' profile
* introduce env variable to set state of dev mode expanded (currently defaults to true)
* remove unnecessary `console.log()` statements and/or replace with proper logging (`@tauri-apps/plugin-log`)

### Motivation

Enhance developer experience, increase readability

### To-do List

- [x] remove outdated commented code
- [x] remove unused feature: change appearance of credential (color, icon)
- [x] add demo history to Ferris' profile
- [x] introduce env variable to set state of dev mode expanded (currently defaults to true)
- [x] remove unnecessary `console.log()` statements and/or replace with proper logging (`@tauri-apps/plugin-log`)
