### ISSUE TITLE
Make `state` parameter in reducers immutable again

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#163]
### Description

As introduced here: https://github.com/impierce/identity-wallet/pull/157#discussion_r1526166365

Several reducers currently have the following signature:
```rust
(mut state: AppState, action: Action) -> Result<AppState, AppError>
```
which need to be replaced with:
```rust
(state: AppState, action: Action) -> Result<AppState, AppError>
```

so that the incoming state is immutable. 

instead of changing fields in a mutable state, a new state needs to be returned like this:
```rust
return Ok(AppState {
    field: changed_value,
    ..state
});
```

### Motivation

Always safer/more idiomatic to keep the state as immutable as possible and only explicitly take ownership over specific fields in order to make them mutable.
This will also be closer to redux pattern principles.

### Resources

#157

### To-do List

- [ ] update: `handle_siopv2_authorization_request`
- [ ] update: `handle_oid4vp_authorization_request`
- [ ] update: `send_credential_request`
- [ ] update: `toggle_dev_mode`
- [ ] update: `create_identity`

**Comment by JelleMillenaar** [comment]
Might make sense to let the same person who does this issue tackle #154
