### ISSUE TITLE
refactor: move superfluous integration testing to unit-tests

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#199]
### Description

Many integration tests will be cleaned up and simplified to unit-tests paired with their respective reducer.
Each feature will still maintain either one or two integration tests that will cover an instance of the entire flow.
All other tests will be moved to unit-tests.

### Motivation

Many of the integration tests are more overcomplicated unit-tests than anything else.

### To-do List

- [ ] Implement easy to use Default::defaults for all AppState fields
- [ ] Move superfluous integration tests to unit tests
- [ ] Create new more complete integration tests where needed.

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [refactor: move superfluous integration testing to unit-tests](https://trello.com/c/D5tPpWfZ/33-refactor-move-superfluous-integration-testing-to-unit-tests)
