### ISSUE TITLE
feat(a11y): Add preference option for date notation

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#205]
### Description

Add a preference option to profile settings through which users can choose how they want their dates displayed.
This can be done quite simply in the frontend, the backend would only have to communicate the chosen date-notation locale.

Besides different countries writing the month before the day or the other way around (month/day/year vs day/month/year) there is also the point of readability for users who might have trouble with smaller notations or number/letter based notation due to dyslexia or discalculia.

The discussion remains if we want to keep shorter notations in smaller fields and longer notations in for example the data/connection specific overviews. This would bring about the questions how this different fields would respond to the locales

Blocked by:
 - [ ] #204 

### Motivation

Adds to the user experience and accessibility (a11y)

### To-do List

- [ ] Shortlist the date notations we want to make available
- [ ] Make ux designs
- [ ] Add the action and reducer
- [ ] Integrate with the frontend

**Comment by maiertech** [comment]
I would say that it's reasonable to expect that a user has sorted out their date preferences in their OS. And UniMe should just use that (possibly customized) OS locale by default for both translations and dates.

Because otherwise, we have to replicate OS functionality to fine tune the locale in the app.

If a user uses `en-US` as their OS-locale, and then switches `nl-NL` inside UniMe, then I think it's ok to display the dates in `nl-NL` and not give a choice to customize how dates are formatted.

**Comment by Oran-Dan** [comment]
I agree. Perhaps we can do some research to what the default options usually are for a11y in regards to people that have difficulty reading because eyesight, dyslexia or discalculia. I expect these solutions to be rather independent from locale.

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [feat(a11y): Add preference option for date notation](https://trello.com/c/yKPk7j4G/36-feata11y-add-preference-option-for-date-notation)

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [chore(frontend): various minor enhancements](https://trello.com/c/u7SRgA5Z/37-chorefrontend-various-minor-enhancements)
