### ISSUE TITLE
chore: Add Dependabot config for frontend

### ISSUE THREAD

**Issue by maiertech** [impierce/identity-wallet#206]
### Description

Add a Dependabot config for the SvelteKit frontend.

### Motivation

Dependencies get outdated quickly. Versions should be bumped regularly to avoid falling behind with dependency updates. Dependabot creates on PR per outdated dependency and allows upgrading them one by one. 

### Resources

https://docs.github.com/en/code-security/dependabot

### To-do List

- [ ] Add Dependabot configuration file.
- [ ] Add config for NPM in `/unime`.
- [ ] Add config for GitHub actions.
