### ISSUE TITLE
chore(frontend): various minor enhancements

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#211]
### Description

See To-do List

### Motivation

Improve UX

### To-do List

- [x] Make the color of the unselected tabs on the bottom (Me - Scan - Activity) brighter, as not they look greyed out/disabled. Will be fixed in https://github.com/impierce/identity-wallet/issues/219.
- [x] Make the entire "Ownership" field during onboarding clickable, instead of only the tiny checkbox itself. Will be implemented in https://github.com/impierce/identity-wallet/issues/221.
- [x] Change password confirmation validation behavior: https://github.com/impierce/identity-wallet/issues/222.
- [ ] Edit empty credentials homepage text (exact desired text still up for discussion)
- [ ] Enlarge font size during onboarding pledges
