### ISSUE TITLE
chore: Refactor Shenron from Dev profile to NGDIL test functions

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#299]
### Description

Currently, Shenron is a completely new profile, deleting all information the user has collected in their current profile. This is not necessary. Instead it should be a list of steps that can trigger NGDIL steps without needing to visit the NGDIL website. In addition, further changes are required to make it more useful and make it work with the latest NGDIL updates.

### Motivation

Prevent unnecessarily loss of data and history in testing scenario's

### Resources

Should automatically fix and supersede: #215 and #218 (and are therefore closed)

### To-do List

- [ ] Rebrand Shenron -> NGDIL 
- [ ] Remove its Dev profile status and simply let it execute NGDIL steps on the current account
- [ ] When a specific step is chosen, as opposed to "Complete Flow", ONLY that step should be executed instead of all steps until that point. 
- [ ] Should work with the latest NGDIL updates (different DID method and signature scheme)
- [ ] Consider cutting down steps, not sure if both the "Add credentials" and "Accept credentials" are useful (and similar).
- [ ] Add user feedback for any errors, timeouts or other issues when executing an NGDIL step

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [chore: Refactor Shenron from Dev profile to NGDIL test functions](https://trello.com/c/1rLRLAhi/48-chore-refactor-shenron-from-dev-profile-to-ngdil-test-functions)
