### ISSUE TITLE
feat: implement secure password management

### ISSUE THREAD

**Issue by nanderstabel** [impierce/identity-wallet#33]
### Description

On each startup of the wallet, there should be a prompt asking for the password which can be used for accessing Stronghold.

This also means that we need be able to use stronghold (via identity.rs?) for signing oid4vc related data. 

### Motivation

Currently we use a hardcoded unsafe password which is obviously not secure. 

### Resources

n/a

### To-do List

- [x] Add a `UserPrompt` asking for password
- [x] Use one single stronghold Client
- [x] Make sure oid4vc related data can be signed using Stronghold.
