### ISSUE TITLE
Trust list for linked vp

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#344]
### Description

The idea is to have a trust list of domain url's, accessible in the settings.

This trust list will be used to perform domain verification for linked VP's.
If a domain is not trusted we don't want to display anything from the linked VP as we cannot guarantee that what is being linked is actually of any value, and presenting it anyway would very much make it look like a valuable trust point.

In dev mode this needs to be editable, meaning we can delete, add and turn on/off the domains on the trust list.
In reg mode its a fixed list, without options

### Motivation

Enhance UX & DX and support linked VP in a more scalable way.

### To-do List

- [x] Add trust list to appstate
- [x] Add Actions & Reducers for the delete, add and toggle functionality
- [x] Add defaults implementation
- [x] Add reset functionality
- [x] Create designs for frontend
- [ ] Implement designs in frontend

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Trust list for linked vp](https://trello.com/c/0mvLHAwI/58-trust-list-for-linked-vp)
