### ISSUE TITLE
Connection Specific Data Overview

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#58]
### Description

Implement the Data tab for a specific connection. It should display both an overview of the data shared and the data received. Data sensitivity is not yet implemented and should be omitted from an initial version, but the design should be extended to also link to the verifiable credentials received from this particular connection. 

### Motivation

Inform the user in a clear way what data was shared and received with a particular connection. 

### Resources

Design for Data-shared:
![image](https://github.com/impierce/identity-wallet/assets/29886335/a69a0161-f30e-4197-9dbe-cbc85da2600f)

### To-do List

- [x] Design Data Shared
- [ ] Implement Data Shared
- [ ] Design Data Received
- [ ] Implement Data Received

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connection Specific Data Overview](https://trello.com/c/fGhEBbVz/11-connection-specific-data-overview)
