### ISSUE TITLE
Add Search to Credentials & Connections 

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#60]
### Description

Add a Search functionalities to the Credentials and Connections pages. The search should feel responsive but doesn't search immediately after each key stroke. Searching should work based on Issuer, Credential Name or Credential Content. 

### Motivation

Improve scalability of the app by finding credentials and connections more easily if we assume large amount of usage. 

### Resources

Example from History Designs: 
![image](https://github.com/impierce/identity-wallet/assets/29886335/3e3c9c73-edc5-4f9d-a2bd-1cea68edb7e5)

### To-do List

- [x] Create Search Logic & Components
- [x] Add functionalities to "Me"
- [x] Add functionalities to "Activity" - Connections

**Comment by Oran-Dan** [comment]
To-Do List - Oran
- [x] Create Search Logic & Components
- [x] Create Sort Logic & Components

**Comment by SoulaAndrikopoulos** [comment]
To-Do List - Soula
- [x] Create Search Logic & Components/
- Iterate on search component's designs
- Implement and build components
 - [x] Create Sort Logic & Components
 - Iterate on sort component's designs
- Implement and build components
 - [x] Add functionalities to "Me"
 - [x] Add functionalities to "Activity" - Connections

**Comment by SoulaAndrikopoulos** [comment]
Add sort component, currently without the grid/list view, and add persistent sorted preference option [see issue 72](https://github.com/impierce/identity-wallet/issues/72).
![★ V2 Dashboard](https://github.com/impierce/identity-wallet/assets/43676124/4d82a468-674c-4226-8da5-488e6338887b)

**Comment by Oran-Dan** [comment]
As discussed in weekly sync, Search Page will be one and the same for connections, credentials and possibly history in the future. To avoid one big pile of search results we will add chips/filters to the search page functionality as specified in issue
Add Chips to Search Functionality #85
