### ISSUE TITLE
Add Cloud back-up and Recovery functionalities

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#61]
### Description

Add the functionality during onboarding to store a back-up file to an existing cloud account on a pre-determined location. We do **not** implement the "Manual" recovery set-up using secrets keys and can be removed from the options. We'll need to consider the logic for frequently backing-up at a fixed interval (or event-driven). Might overall need more alignment. 

### Motivation

Counter-act the most frequently asked question: What to do when someone loses his phone. Just recover your back-up ;) 

### Resources

Flows are displayed in the Figma.

### To-do List

- [ ] Implement Recovery Set-up (Cloud) Screens
- [ ] Support Google Drive and iCloud (Consider others?)
- [ ] Implement Event-driven and/or fixed interval back-up logic
- [ ] Recover from Cloud Logic & Screens
- [ ] Consider & Implement Manual Back-up (File Download & Upload)

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Cloud back-up and Recovery functionalities](https://trello.com/c/oxCciUJe/12-add-cloud-back-up-and-recovery-functionalities)
