### ISSUE TITLE
Add History

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#62]
### Description

Add History feature into the wallet which showcases the following different events: Connecting, Sharing Data and Receiving Data. The events are connected to the Connection and should display the correct logo and display name or website. If not implemented yet, the events must first be tracked and stored. We should consider secure storage vs fast storage for these events. 

### Motivation

While we doubt the feature will be used significantly, it is a vital tool and protection against over-requesting data by connections. The history can give insight into abuse and may later be extended with reporting logic. In addition, it might be useful for users to view their history of events for a range of reasons.

### Resources

Main History Page:
![image](https://github.com/impierce/identity-wallet/assets/29886335/5c9fbb07-dc0f-4511-9428-7c395678fe56)

Connection Specific History:
![image](https://github.com/impierce/identity-wallet/assets/29886335/bc01b74d-ffc3-4d1b-96c7-ee5526ec6c37)

### To-do List

- [ ] Track Events and Store them (Securely or efficiently?) - Care to include signed request?
- [ ] Implement History overview
- [ ] Implement filtered History overview by Connection
- [ ] Support search / filter / order logic based on UX discussion
