### ISSUE TITLE
Fix Keyboard overlap with Content

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#63]
### Description

Fix the Keyboard pop-up on Android (& IOS?) to overlap content.

### Motivation

Show intended Content to the User

### Resources

Example Profile Name:
![image](https://github.com/impierce/identity-wallet/assets/29886335/a93fed63-f8f1-4627-b347-da188dc6633d)

Intended Password Content:
![image](https://github.com/impierce/identity-wallet/assets/29886335/668e9372-f184-445d-ae19-2c12925c5942)

Shown Password Content with Keyboard open:
![image](https://github.com/impierce/identity-wallet/assets/29886335/d24593c8-518f-4820-bd75-b27966132c55)

### To-do List

- [x] Verify the Issue to exist on IOS
- [ ] Automatically scroll the content such that all relevant information is on screen when keyboard is engaged
- [ ] Alter Content to fit on the screen with the keyboard engaged (Maintain consistency) if too much content exists

**Comment by M-Adam-Hus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Keyboard overlap with Content](https://trello.com/c/xJG6gNlE/13-fix-keyboard-overlap-with-content)

**Comment by maiertech** [comment]
On iOS you can reach any part of the current page by scrolling, including the Continue button. In below screenshot, the big white space below the Continue button is where the keyboard sits (it does not show up in the screenshot). When scrolling all the way down to the bottom of the page, the Continue button sits on to of the keyboard.

Therefore, not an issue on iOS.

<img src="https://github.com/user-attachments/assets/ed70ca0d-f103-42ab-9c0e-fc7a3070e36b" width="256" />

**Comment by maiertech** [comment]
Should have keyboard support to hit the Continue button.

On a A15 with Android 14 it behaves like this: When the keyboard is out, Android sizes the webview to available space above the keyboard or to content size, whichever is bigger. This means that in the UniMe onboarding dialog sometimes you are lucky and the Continue button is above the keyboard and sometimes its under the keyboard.

Since the Android keyboard does not push the webvie upwards but only overlays it, it will probably not be possible to fix this in the sense that you can force relevant parts to display above the keyboard.

**Comment by maiertech** [comment]
Check out 9292 reisplanner.
