### ISSUE TITLE
Add Dutch language to UniMe

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/identity-wallet#66]
### Description

Add Dutch translations to the app via i18n.
This includes replacing all hard-coded English with placeholders, which can be filled in by any language eventually.
The Dutch translations will be located in a folder named 'nl' in a single 'index.ts' file within the 'i18n' folder in the front-end section.

### Motivation

Make the app scalable to all languages, starting with Dutch.

### Resources

https://github.com/ivanhofer/typesafe-i18n

### To-do List

- [ ] Replace hard-coded English with placeholders.
- [ ] Move the hard-coded English to the 'en/index.ts' file.
- [ ] Fill in 'nl/index.ts' file with the Dutch Translations.
