### ISSUE TITLE
Automated frontend testing

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#67]
### Description

We want to assure all pages and elements are displayed as expected without having to manually click through all flows and inspect if every feature works.

### Motivation

Greatly improved debugging, quality assurance, save time.

### To-do List

- [ ] Pick a testing setup (libraries, frameworks, etc.)
- [ ] Write some tests
- [ ] Document setup and guide on how to test

**Comment by daniel-mader** [comment]
According to the docs [Playwright is not supported](https://tauri.app/v1/guides/getting-started/setup/sveltekit/#create-the-frontend), also [Webdriver support for Tauri is still in pre-alpha](https://beta.tauri.app/guides/test/webdriver). Currently, we're left with `vitest` and [mocking Tauri APIs](https://beta.tauri.app/guides/test/mocking).

**Comment by habibur4340** [comment]
Hey @daniel-mader
Automating testing ensures all pages/elements function as expected without manual checks. Consider [Apidog](https://apidog.com/) for streamlined testing and documentation, aiding in quality assurance and time-saving. Start by choosing suitable testing frameworks, writing tests, and creating a comprehensive guide.

**Comment by maiertech** [comment]
Adding `Blocked` because we count on Tauri to add the infrastructure for automated front-end testing.
