### ISSUE TITLE
Upgrade Listview with Images

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#78]
### Description

Upgrade the listview for the credentials to include images as per the designs. The images should be taken from the following resources in order of priority (if no image is available, move to the next in the priority):
- During VCI, a credential specific image may be provided (currently non-standard as far as I know)
- The .well-known document of the Issuer may contain an Issuer image to be used
- The .well-known document may link to a domain, this likely has a favicon to utilize
- Otherwise, render a default credential icon

Similarly for Badges:
- Most badges will be Issued with Images
- Otherwise render an image from the Issuer (.well-known)
- Lastly use the favicon
- Otherwise render a default badge icon

### Motivation

Better designs :) 

### Resources

Reference UX designs 

### To-do List

- [x] Query and store images during VCI process from aforementioned resources until a suitable image is found
- [x] Upgrade the Listview to include the images
- [x] Test with NGDIL demo to see if images properly load
