### ISSUE TITLE
feat: SvelteKit

### ISSUE THREAD

**Issue by daniel-mader** [impierce/identity-wallet#8]
### Description

Explore if SvelteKit should be used instead of pure Svelte.

### Motivation

The SvelteKit-native router is considered easier to handle than the currently used third-party library (`svelte-navigator`).
Also, an improvement in the developer experience is expected through using SvelteKit (such as relative paths, e.g. `$lib`).

### To-do List

- [ ] create a parallel branch, install new SvelteKit from scratch
- [ ] move components and logic to SvelteKit
- [ ] extensive testing, further exploration (mainly routing and rendering capabilites, async, fetch, etc.)
