### ISSUE TITLE
Add `did:iota` resolution

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#90]
### Description

Add support for the resolution of the `did:iota` method such that did's during SIOPv2, OpenID4VCI or OpenID4VP interactions can be resolved and credentials signed by this method can be verified.

### Motivation

Add support for issuers, relying parties and verifiers that utilize the IOTA or SMR network. 

### Resources

- [Method Specification](https://wiki.iota.org/identity.rs/references/specifications/iota-did-method-spec/)
- [Method Implementation](https://github.com/iotaledger/identity.rs/tree/main/identity_iota)

### To-do List

- [x] Implement `did:iota` verification
- [x] Test against a SIOPv2, OpenID4VCI and OpenID4VP interaction from an `did:iota` identity
- [x] Add default node list
- [ ] Allow user management of node list?
- [x] Test against IOTA, SMR and RMS networks
