### ISSUE TITLE
Add `did:web` resolution

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#93]
### Description

Add support for the resolution of the `did:web` method such that did's during SIOPv2, OpenID4VCI or OpenID4VP interactions can be resolved and credentials signed by this method can be verified.

### Motivation

One step closer towards full compatibility with the Dutch Blockchain Coalition's DIIP profile.

### Resources

- [DIIP Profile](https://github.com/DutchBlockchainCoalition/DIIP/discussions/12)

### To-do List

- [x] Find or implement `did:web` crate (align with agent requirements)
- [x] Implement `did:web` verification
- [ ] Test against a SIOPv2, OpenID4VCI and OpenID4VP interaction from an `did:web` identity
