### ISSUE TITLE
Add full support for `did:jwk`

### ISSUE THREAD

**Issue by JelleMillenaar** [impierce/identity-wallet#94]
### Description

As opposed to #90 and #93, this issue requires full support for `did:jwk`, which includes identity creation and using it as the identity for the holder. It should work similarly as `did:key`. The app should generate a `did:jwk` as soon as it realizes it needs one.

### Motivation

One step closer towards full compatibility with the Dutch Blockchain Coalition's DIIP profile.

### Resources

- [DIIP Profile](https://github.com/DutchBlockchainCoalition/DIIP/discussions/12)
- [DID Method Spec](https://github.com/quartzjer/did-jwk/blob/main/spec.md)

### To-do List

- [x] Find or implement `did:jwk` crate (align with agent requirements)
- [x] Add `did:jwk` creation and usage in SIOPv2, OpenID4VCI and OpenID4VP interactions
- [x] Add `did:jwk` verification
